name: "Auto Update"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
env:
  TZ: Asia/Shanghai


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Get Package
        run: |
            git clone https://github.com/immortalwrt/luci -b openwrt-23.05 ${GITHUB_WORKSPACE}/luci
            git clone https://github.com/immortalwrt/packages -b openwrt-23.05 ${GITHUB_WORKSPACE}/packages
            if [ -d ${GITHUB_WORKSPACE}/luci/applications/luci-app-vlmcsd ];then
                rm -rf ${GITHUB_WORKSPACE}/luci-app-vlmcsd
                cp -rf ${GITHUB_WORKSPACE}/luci/applications/luci-app-vlmcsd ${GITHUB_WORKSPACE}/
            fi
            if [ -d ${GITHUB_WORKSPACE}/packages/net/vlmcsd ];then
                rm -rf ${GITHUB_WORKSPACE}/vlmcsd
                cp -rf ${GITHUB_WORKSPACE}/packages/net/vlmcsd ${GITHUB_WORKSPACE}/
            fi
            rm -rf ${GITHUB_WORKSPACE}/luci ${GITHUB_WORKSPACE}/packages

      - name: Creat Message
        id: msg
        run: |
            echo "commit_message=Update $(date +"%Y-%m-%d %H:%M:%S")" >> "$GITHUB_OUTPUT"
 
      - name: Apply Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: ${{ steps.msg.outputs.commit_message }}
         branch: main
         commit_user_name: hubbylei
         commit_user_email: hubbylei@hubbylei.dynu.net
         commit_author: hubbylei <hubbylei@hubbylei.dynu.net>

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 5
